// <auto-generated />
using System;
using HastaMemnuniyet.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HastaMemnuniyet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AksiyonGecmisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("AksiyonId")
                        .HasColumnType("integer");

                    b.Property<int>("EskiDurum")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("YeniDurum")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AksiyonId");

                    b.ToTable("AksiyonGecmisleri", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Anket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("AnaSurumAnketId")
                        .HasColumnType("integer");

                    b.Property<int>("AnketTuru")
                        .HasColumnType("integer");

                    b.Property<string>("GizlilikMetni")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SurumNo")
                        .HasColumnType("integer");

                    b.Property<int>("TahminiSureDakika")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Anketler", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketCevabi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("BoolDegeri")
                        .HasColumnType("boolean");

                    b.Property<string>("MetinDegeri")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int?>("PuanDegeri")
                        .HasColumnType("integer");

                    b.Property<int?>("SecenekId")
                        .HasColumnType("integer");

                    b.Property<string>("SeciliSecenekIdleri")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.Property<int>("YanitId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("YanitTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("SecenekId");

                    b.HasIndex("SoruId");

                    b.HasIndex("YanitId");

                    b.ToTable("AnketCevaplari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketDaveti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnketId")
                        .HasColumnType("integer");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<int>("GonderimKanali")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<int>("HatirlatmaSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HizmetTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OlusturanKullaniciId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("SonGecerlilikTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TelefonHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("AnketId");

                    b.HasIndex("BirimId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("Durum");

                    b.HasIndex("HastaneId");

                    b.HasIndex("TelefonHash");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("AnketDavetleri", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketSoruSecenegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MetinDegeri")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<int>("SoruId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.ToTable("AnketSoruSecenekleri", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketSorusu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("AnketId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("KosulBagliSoruId")
                        .HasColumnType("integer");

                    b.Property<string>("KosulDegeri")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("MaksimumKarakterSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("PuanlamaAltSinir")
                        .HasColumnType("integer");

                    b.Property<int?>("PuanlamaUstSinir")
                        .HasColumnType("integer");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("SoruTipi")
                        .HasColumnType("integer");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("KosulBagliSoruId");

                    b.HasIndex("AnketId", "SiraNo");

                    b.ToTable("AnketSorulari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketYaniti", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AnketId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BaslamaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int>("DavetId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<bool>("GecerliMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("KullaniciAjan")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AnketId");

                    b.HasIndex("DavetId");

                    b.HasIndex("HastaneId");

                    b.HasIndex("TamamlanmaTarihi");

                    b.ToTable("AnketYanitlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Birim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<string>("Kod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("HastaneId", "Ad");

                    b.ToTable("Birimler", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.DenetimKaydi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Detay")
                        .HasColumnType("text");

                    b.Property<string>("EskiDeger")
                        .HasColumnType("text");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KayitId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("KullaniciAdi")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("KullaniciId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<string>("Tablo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YeniDeger")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Tarih");

                    b.ToTable("DenetimKayitlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Doktor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("Doktorlar", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.DoktorBirim", b =>
                {
                    b.Property<int>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.HasKey("DoktorId", "BirimId");

                    b.HasIndex("BirimId");

                    b.ToTable("DoktorBirimleri", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Hastane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Adres")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Telefon")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.ToTable("Hastaneler", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.IyilestirmeAksiyonu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("HedefTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KapanisNotu")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("KritikGeriBildirimId")
                        .HasColumnType("integer");

                    b.Property<string>("OlusturanKullaniciId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Oncelik")
                        .HasColumnType("integer");

                    b.Property<string>("SorumluKullaniciId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("HastaneId");

                    b.HasIndex("KritikGeriBildirimId");

                    b.HasIndex("SorumluKullaniciId");

                    b.ToTable("IyilestirmeAksiyonlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KritikGeriBildirim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("CevapId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<int>("KuralId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("YanitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CevapId");

                    b.HasIndex("HastaneId");

                    b.HasIndex("KuralId");

                    b.HasIndex("OlusturulmaTarihi");

                    b.HasIndex("YanitId");

                    b.ToTable("KritikGeriBildirimler", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KritikGeriBildirimKurali", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("AnahtarKelimeler")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("AnketId")
                        .HasColumnType("integer");

                    b.Property<int?>("EsikDegeri")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("HedefSecenekId")
                        .HasColumnType("integer");

                    b.Property<int>("KuralTipi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SoruId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("AnketId");

                    b.HasIndex("SoruId");

                    b.ToTable("KritikGeriBildirimKurallari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KullaniciBirimKapsami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BirimId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("KullaniciId", "BirimId")
                        .IsUnique();

                    b.ToTable("KullaniciBirimKapsamlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KullaniciHastaneKapsami", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HastaneId");

                    b.HasIndex("KullaniciId", "HastaneId")
                        .IsUnique();

                    b.ToTable("KullaniciHastaneKapsamlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.QrAnketKampanyasi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<int>("AnketId")
                        .HasColumnType("integer");

                    b.Property<int?>("BirimId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoktorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HastaneId")
                        .HasColumnType("integer");

                    b.Property<int>("KullanimSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SonKullanmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AktifMi");

                    b.HasIndex("AnketId");

                    b.HasIndex("BirimId");

                    b.HasIndex("DoktorId");

                    b.HasIndex("HastaneId");

                    b.ToTable("QrAnketKampanyalari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.SistemAyari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Anahtar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Deger")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("GuncellenmeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kategori")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Anahtar")
                        .IsUnique();

                    b.ToTable("SistemAyarlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.SmsGonderimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DavetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GonderimTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SmsDurumu")
                        .HasColumnType("integer");

                    b.Property<string>("SmsYaniti")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("TelefonHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DavetId");

                    b.ToTable("SmsGonderimKayitlari", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AksiyonGecmisi", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.IyilestirmeAksiyonu", "Aksiyon")
                        .WithMany("Gecmis")
                        .HasForeignKey("AksiyonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aksiyon");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketCevabi", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketSoruSecenegi", "Secenek")
                        .WithMany()
                        .HasForeignKey("SecenekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketSorusu", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketYaniti", "Yanit")
                        .WithMany("Cevaplar")
                        .HasForeignKey("YanitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Secenek");

                    b.Navigation("Soru");

                    b.Navigation("Yanit");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketDaveti", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Anket", "Anket")
                        .WithMany("Davetler")
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Hastane", "Hastane")
                        .WithMany()
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anket");

                    b.Navigation("Birim");

                    b.Navigation("Doktor");

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketSoruSecenegi", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketSorusu", "Soru")
                        .WithMany("Secenekler")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketSorusu", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Anket", "Anket")
                        .WithMany("Sorular")
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketSorusu", "KosulBagliSoru")
                        .WithMany()
                        .HasForeignKey("KosulBagliSoruId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Anket");

                    b.Navigation("KosulBagliSoru");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketYaniti", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketDaveti", "Davet")
                        .WithMany("Yanitlar")
                        .HasForeignKey("DavetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davet");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Birim", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Hastane", "Hastane")
                        .WithMany("Birimler")
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.DoktorBirim", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Birim", "Birim")
                        .WithMany("DoktorBirimleri")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Doktor", "Doktor")
                        .WithMany("DoktorBirimleri")
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Doktor");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.IyilestirmeAksiyonu", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.KritikGeriBildirim", "KritikGeriBildirim")
                        .WithMany("Aksiyonlar")
                        .HasForeignKey("KritikGeriBildirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", "SorumluKullanici")
                        .WithMany()
                        .HasForeignKey("SorumluKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KritikGeriBildirim");

                    b.Navigation("SorumluKullanici");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KritikGeriBildirim", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketCevabi", "Cevap")
                        .WithMany()
                        .HasForeignKey("CevapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.KritikGeriBildirimKurali", "Kural")
                        .WithMany()
                        .HasForeignKey("KuralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketYaniti", "Yanit")
                        .WithMany()
                        .HasForeignKey("YanitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cevap");

                    b.Navigation("Kural");

                    b.Navigation("Yanit");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KritikGeriBildirimKurali", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Anket", "Anket")
                        .WithMany()
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketSorusu", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Anket");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KullaniciBirimKapsami", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Birim", "Birim")
                        .WithMany("KullaniciKapsamlari")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", "Kullanici")
                        .WithMany("BirimKapsamlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KullaniciHastaneKapsami", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Hastane", "Hastane")
                        .WithMany("KullaniciKapsamlari")
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", "Kullanici")
                        .WithMany("HastaneKapsamlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hastane");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.QrAnketKampanyasi", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.Anket", "Anket")
                        .WithMany()
                        .HasForeignKey("AnketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Doktor", "Doktor")
                        .WithMany()
                        .HasForeignKey("DoktorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HastaMemnuniyet.Domain.Entities.Hastane", "Hastane")
                        .WithMany()
                        .HasForeignKey("HastaneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Anket");

                    b.Navigation("Birim");

                    b.Navigation("Doktor");

                    b.Navigation("Hastane");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.SmsGonderimKaydi", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.AnketDaveti", "Davet")
                        .WithMany("SmsGonderimKayitlari")
                        .HasForeignKey("DavetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Davet");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Anket", b =>
                {
                    b.Navigation("Davetler");

                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketDaveti", b =>
                {
                    b.Navigation("SmsGonderimKayitlari");

                    b.Navigation("Yanitlar");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketSorusu", b =>
                {
                    b.Navigation("Secenekler");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.AnketYaniti", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Birim", b =>
                {
                    b.Navigation("DoktorBirimleri");

                    b.Navigation("KullaniciKapsamlari");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Doktor", b =>
                {
                    b.Navigation("DoktorBirimleri");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.Hastane", b =>
                {
                    b.Navigation("Birimler");

                    b.Navigation("KullaniciKapsamlari");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.IyilestirmeAksiyonu", b =>
                {
                    b.Navigation("Gecmis");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.KritikGeriBildirim", b =>
                {
                    b.Navigation("Aksiyonlar");
                });

            modelBuilder.Entity("HastaMemnuniyet.Domain.Entities.UygulamaKullanicisi", b =>
                {
                    b.Navigation("BirimKapsamlari");

                    b.Navigation("HastaneKapsamlari");
                });
#pragma warning restore 612, 618
        }
    }
}
